ENTER_PLAYER = "ENTER_PLAYER"

START_GAME = "START_GAME"

ANSWER_QUESTION = "ANSWER_QUESTION"

NEXT_ROUND = "NEXT_ROUND"

UPDATE_TIMER = "UPDATE_TIMER"

END_GAME = "END_GAME"

RESET_GAME = "RESET_GAME"
